# begin-of-file

[program:goldfisher]
process_name=%(program_name)s_%(process_num)02d
directory=/home/kolyma/Workspace/goldfisher.de/files

serverurl=http://127.0.0.1:8005
port=127.0.0.1:8005

command=/home/kolyma/Workspace/goldfisher.de/files/app.sh

user=root
numprocs=1
redirect_stderr=true
autostart=true
autorestart=true
stderr_logfile=/home/kolyma/logs/goldfisher.de/supervisor.error.log
stdout_logfile=/home/kolyma/logs/goldfisher.de/supervisor.output.log
stopasgroup=true
killasgroup=true

# end-of-file
