server {
    server_name vagrant.goldfisher.de;
       
    listen 80;

    error_log  /home/kolyma/logs/goldfisher.de/error.nginx.log warn; 
    access_log /home/kolyma/logs/goldfisher.de/access.nginx.log;

    server_tokens             off;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    
    if ( $request_method !~ ^(GET|HEAD|POST|PUT)$ ) { return 405; }

    root /home/kolyma/Workspace/goldfisher.de/files/docs;
    index index.xhtml; 

    location ~* \.(ico|css|jss|pdf|png|gif|jpg|jpe|jpeg|webp|html|htm|svg|gpx|ogg|mp3|mp4|mov)$ {
      expires 365d;
      gzip on;
      gzip_min_length 1000;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_proxied any;
      gzip_types 
         text/plain text/html text/htm text/css text/javascript 
         application/xml application/pdf application/gpx+xml 
         image/png image/gif image/jpg image/jpeg image/webp image/webp image/x-icon
         audio/ogg video/mp4 video/quicktime;
    }
    
    location / {
        gzip on;
        proxy_pass http://127.0.0.1:8005;
    }
    
}

